### ISSUE TITLE
Hello everyone!

### ISSUE THREAD

**Issue by Teddy-van-Jerry** [T-V-J/Fractal_Designer#1]
@T-V-J/frd-dev Welcome to TVJ Group, check out our group website https://group.teddy-van-jerry.org!

**Comment by the-shy-lsc** [comment]
soga

**Comment by The-never-lemon** [comment]
Wow

**Comment by shenzihang123** [comment]
acquérir

**Comment by Teddy-van-Jerry** [comment]
Wonderful. It is estimated that we will start our work tomorrow. Today you can have a glimpse at how Qt is worked.

**Comment by The-never-lemon** [comment]
Oh god
