### ISSUE TITLE
Fractal Designer 5.6.3-alpha Bugs Report and Features Suggestions

### ISSUE THREAD

**Issue by Teddy-van-Jerry** [T-V-J/Fractal_Designer#5]
@T-V-J/frd-dev After testing the 5.6.3-alpha version, please report the bugs you find. You can also suggest new features here.

**Comment by the-shy-lsc** [comment]
**Feature Suggestion**: Auto Refresh after setting the colors.

**Comment by the-shy-lsc** [comment]
**Feature Suggestion**: Add axes at preview image.

**Comment by the-shy-lsc** [comment]
**Bug**: Em, the y-direction of preview image seems to be inversed.
![bug](https://user-images.githubusercontent.com/75214884/125158309-d9cd6400-e1a2-11eb-8f28-906781ef13d4.png)

**Comment by the-shy-lsc** [comment]
**Feature Suggestion** of Route Tool
- Auto Refresh when scrolling the mouse
- Axes need numbers

**Comment by Teddy-van-Jerry** [comment]
> **Bug**: Em, the y-direction of preview image seems to be inversed.
> ![bug](https://user-images.githubusercontent.com/75214884/125158309-d9cd6400-e1a2-11eb-8f28-906781ef13d4.png)

@the-shy-lsc I have fixed that, not a big problem!
![After fixing](https://user-images.githubusercontent.com/70827985/125163343-4a827980-e1bf-11eb-8f3d-52b70d3fb3b4.png)

**Comment by Teddy-van-Jerry** [comment]
**Bug**: Default value for Burning Ship Fractal error.

**Comment by shenzihang123** [comment]
I'm now running into a computer crash due to the imaging-creating process, now it has created 1386/1440 images, but the app does't respond to me anymore.

**Comment by shenzihang123** [comment]
tough yet fruitful

**Comment by Teddy-van-Jerry** [comment]
> I'm now running into a computer crash due to the imaging-creating process, now it has created 1386/1440 images, but the app does't respond to me anymore.

Just wait patiently and if your computer is not competent, change the thread number.
![Change Thread Number](https://user-images.githubusercontent.com/70827985/125169194-a22ede00-e1db-11eb-8973-30d058ca9df0.jpg)
